### ISSUE TITLE
Cannot create admin nextcloud user, it fails to connect to the database

### ISSUE THREAD

**Issue by Orion3k** [chrisbeardy/nextcloud-docker-raspberrypi-tutorial#3]
During the admin account creation in nextcloud it fails to connect to the database, the error is the following:

Error while trying to create admin user: Failed to connect to the database: An exception occurred in the driver: SQLSTATE[HY000] [2002] Connection refused

I used the docker-compose file you proposed and i followed all the prevoius steps.
Then i tried to make some changes too, i tried with only the root user in the db but the problem keeps occuring.
Thanks in advance for the support!

**Comment by lterrac** [comment]
I have the exact problem too. 🙏🏻 🙏🏻

**Comment by chrisbeardy** [comment]
hello, are you using the latest commit with nginx proxy manager and the following compose:

```
version: '3'

volumes:
  nextcloud-data:
  nextcloud-db:

networks:
  frontend:
    external:
      name: proxy
  backend:

services:

  nextcloud-app:
    image: nextcloud
    restart: always
    volumes:
      - nextcloud-data:/var/www/html
    environment:
      - MYSQL_PASSWORD=change_me_please
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_HOST=nextcloud-db
      - PHP_UPLOAD_LIMIT=10G
      - PHP_MEMORY_LIMIT=512M
    networks:
      - frontend
      - backend

  nextcloud-db:
    image: mariadb
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - nextcloud-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=change_me_please
      - MYSQL_PASSWORD=change_me_please
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    networks:
      - backend
```

If so, is the exception is happening when the docker conatiner is created? or you can load in https://your-domain but then it won't let you create a user in nextcloud? is the nextcloud database set up correctly to point at "nextcloud-db". 

Maybe I should specify the port for the database and that nextcloud depends on the database into the docker compose.
